In [10]:
#QUESTION 1
#create a class employee
class Employee:
    #create a datamember to count the no.of employees
    no_of_employees = 0

    #create a constructor to initialize name,family,salary,department
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1


    #create a function to average salary
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
    

#create a fulltime emlpoyee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee) :

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("full time employee Benefits.")
    

#create the instances of Fulltime Employee class and employee class and call their member functions
def main():
    employees = []
    fte1 = FulltimeEmployee("E1", "Family1", 90000, "CSE")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("E2", "Family2", 70000, "IT")
    employees.append(fte2)
    emp1 = Employee("E3", "Family3", 300000, "CIS")
    employees.append(emp1)
    emp2 = Employee("E4", "Family4", 20000, "BD")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

full time employee Benefits.
Average salary: 120000.0


In [7]:
#QUESTION2 
#create a randomm vector of size 20 having only float in the range 1-20
import numpy as np
x=np.random.uniform(1,20,20)
print("Original array:")
print(x)
#reshape the array to 4 by 5
x1=x.reshape(3,5)
print("Reshaped Array: ")
print(x1)
#replace the max in each row by 0
x1[np.arange(len(x1)), x1.argmax(1)]=0
print("Maximum value replaced by 0:")
print(x1)

Original array:
[ 4.44048401  2.05942195 12.73659306  9.1296154  11.1093907  11.19137773
  2.71486607 13.12790365 13.50100704  7.01970149  5.95924017  8.36688688
  8.66076456 11.12120543  5.55340687]
Reshaped Array: 
[[ 4.44048401  2.05942195 12.73659306  9.1296154  11.1093907 ]
 [11.19137773  2.71486607 13.12790365 13.50100704  7.01970149]
 [ 5.95924017  8.36688688  8.66076456 11.12120543  5.55340687]]
Maximum value replaced by 0:
[[ 4.44048401  2.05942195  0.          9.1296154  11.1093907 ]
 [11.19137773  2.71486607 13.12790365  0.          7.01970149]
 [ 5.95924017  8.36688688  8.66076456  0.          5.55340687]]
